export const YrWeatherSymbols = {
  clearsky_day: "klarvær",
  clearsky_night: "klarvær",
  fair_day: "lettskyet",
  fair_night: "lettskyet",
  partlycloudy_day: "delvis skyet",
  partlycloudy_night: "delvis skyet",
  cloudy: "overskyet",
  rainshowers_day: "regnbyger",
  rainshowers_night: "regnbyger",
  rainshowersandthunder_day: "regnbyger og torden",
  rainshowersandthunder_night: "regnbyger og torden",
  sleetshowers_day: "sluddbyger",
  sleetshowers_night: "sluddbyger",
  snowshowers_day: "snøbyger",
  snowshowers_night: "snøbyger",
  rain: "regn",
  heavyrain: "kraftig regn",
  heavyrainandthunder: "kraftig regn og torden",
  sleet: "sludd",
  snow: "snø",
  snowandthunder: "snø og torden",
  fog: "tåke",
  sleetshowersandthunder_day: "sluddbyger og torden",
  sleetshowersandthunder_night: "sluddbyger og torden",
  snowshowersandthunder_day: "snøbyger og torden",
  snowshowersandthunder_night: "snøbyger og torden",
  rainandthunder: "regn og torden",
  sleetandthunder: "sludd og torden",
  lightrainshowersandthunder_day: "lette regnbyger og torden",
  lightrainshowersandthunder_night: "lette regnbyger og torden",
  heavyrainshowersandthunder_day: "kraftige regnbyger og torden",
  heavyrainshowersandthunder_night: "kraftige regnbyger og torden",
  lightssleetshowersandthunder_day: "lette sluddbyger og torden",
  lightssleetshowersandthunder_night: "lette sluddbyger og torden",
  heavysleetshowersandthunder_day: "kraftige sluddbyger og torden",
  heavysleetshowersandthunder_night: "kraftige sluddbyger og torden",
  lightssnowshowersandthunder_day: "lette snøbyger og torden",
  lightssnowshowersandthunder_night: "lette snøbyger og torden",
  heavysnowshowersandthunder_day: "kraftige snøbyger og torden",
  heavysnowshowersandthunder_night: "kraftige snøbyger og torden",
  lightrainandthunder: "lett regn og torden",
  lightsleetandthunder: "lett sludd og torden",
  heavysleetandthunder: "kraftig sludd og torden",
  lightsnowandthunder: "lett snø og torden",
  heavysnowandthunder: "kraftig snø og torden",
  lightrainshowers_day: "lette regnbyger",
  lightrainshowers_night: "lette regnbyger",
  heavyrainshowers_day: "kraftige regnbyger",
  heavyrainshowers_night: "kraftige regnbyger",
  lightsleetshowers_day: "lette sluddbyger",
  lightsleetshowers_night: "lette sluddbyger",
  heavysleetshowers_day: "kraftige sluddbyger",
  heavysleetshowers_night: "kraftige sluddbyger",
  lightsnowshowers_day: "lette snøbyger",
  lightsnowshowers_night: "lette snøbyger",
  heavysnowshowers_day: "kraftige snøbyger",
  heavysnowshowers_night: "kraftige snøbyger",
  lightrain: "lett regn",
  lightsleet: "lett sludd",
  heavysleet: "kraftig sludd",
  lightsnow: "lett snø",
  heavysnow: "kraftig snø",
};
